# If your MATLAB version is not listed in here, here is how to determine the compilation flags
# Try to run the mex command on one of the files (e.g. src/imas_close.c) and look at the flags used in the commands (for the mex command the -v flag - to display more information - and the -n flag - to perform a dry-run only - may be useful).
# For versions prior to R2015a, the define flag -DNO_MXISSCALAR needs to be added.
# If present, replace the -ansi flag with -std=c99.
# For old versions (~< 2015a) use the -largeArrayDims with the mex command on 64-bit platforms.
# Sometimes an additional file from the matlab directory is compiled and added to the binary at link time. The path of this file needs to be added to the MEXSRC variable. Look for example to R2008b and R2017a-R2018b.
# Note also that generally MEX-files compiled with one version of MATLAB will be compatible with future versions. The inverse is not guaranteed.



# Check we have a valid version
ifeq ("","$(MATLAB)")
  ifneq ("","$(EBROOTMATLAB)")
    MATLAB=$(EBROOTMATLAB)
  else
    $(error Empty MATLAB variable. Please specify your MATLAB root directory using the MATLAB variable.)
  endif
endif

# Try to guess MATLAB_VERSION from the loaded module
ifeq ("","$(MATLAB_VERSION)")
  MATLAB_VERSION=$(shell echo $$LOADEDMODULES | gawk 'BEGIN { RS=":"; FS="/" } tolower($$1) ~ /matlab/ { gsub("[Rr]",""); print tolower($$2) }')
endif

# Check we have a valid version
ifeq ("","$(MATLAB_VERSION)")
  $(error Empty MATLAB_VERSION variable . Please specify your MATLAB version using the MATLAB_VERSION variable.)
endif
TESTED_VERSIONS=2008b 2010a 2010b 2011a 2011b 2012a 2012b 2013a 2013b 2014a 2014b 2015a 2015b 2016a 2016b 2017a 2017b 2018a 2018b
ifeq ("","$(findstring $(MATLAB_VERSION),$(TESTED_VERSIONS))")
  $(error "This MATLAB version (MATLAB_VERSION: $(MATLAB_VERSION)) has not been tested yet. Please add the necessary compiler information in the Makefile.flags file or use one of the following versions: $(TESTED_VERSIONS).")
endif

# R2008b 7.7.0
ifeq ("2008b","$(strip $(MATLAB_VERSION))")
  CFLAGS=-std=c99 -fexceptions -fPIC -fno-omit-frame-pointer -pthread
  CFLAGS+= -D_GNU_SOURCE -DMATLAB_MEX_FILE -DNO_MXISSCALAR
  CFLAGS+= -I"$(MATLAB)/extern/include" -I"$(MATLAB)/simulink/include"
  CFLAGS_OPTIM=-O -DNDEBUG
  CFLAGS_DEBUG=-g
  LDFLAGS=-pthread -Wl,--no-undefined -Wl,-rpath-link,$(MATLAB)/bin/glnxa64 -shared  -L"$(MATLAB)/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -Wl,--version-script,"$(MATLAB)/extern/lib/glnxa64/mexFunction.map"
  LDFLAGS_OPTIM=-O
  LDFLAGS_DEBUG=-g
  MEXSRC=$(MATLAB)/extern/src/mexversion.c
endif

# R2010a 7.10.0
# R2010b 7.11.0
# R2011a 7.12.0
# R2011b 7.13.0
# R2012a 7.14.0
# R2012b 8.0.0
# R2013a 8.1.0
# R2013b 8.2.0
# R2014a 8.3.0
# R2014b 8.4.0
ifneq ("","$(findstring $(MATLAB_VERSION),2010a 2010b 2011a 2011b 2012a 2012b 2013a 2013b 2014a 2014b)")
  CFLAGS=-std=c99 -fexceptions -fPIC -fno-omit-frame-pointer -pthread
  CFLAGS+= -D_GNU_SOURCE -DMATLAB_MEX_FILE -DNO_MXISSCALAR
  CFLAGS+= -I"$(MATLAB)/extern/include" -I"$(MATLAB)/simulink/include"
  CFLAGS_OPTIM=-O -DNDEBUG
  CFLAGS_DEBUG=-g
  LDFLAGS=-pthread -Wl,--no-undefined -Wl,-rpath-link,$(MATLAB)/bin/glnxa64 -shared  -L"$(MATLAB)/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -Wl,--version-script,"$(MATLAB)/extern/lib/glnxa64/mexFunction.map"
  LDFLAGS_OPTIM=-O
  LDFLAGS_DEBUG=-g
  MEXSRC=
endif

# R2015a 8.5.0
# R2015b 8.6.0
# R2016a 9.0.0
ifneq ("","$(findstring $(MATLAB_VERSION),2015a 2015b 2016a)")
  CFLAGS=-std=c99 -fexceptions -fPIC -fno-omit-frame-pointer -pthread
  CFLAGS+= -D_GNU_SOURCE -DMATLAB_MEX_FILE
  CFLAGS+= -I"$(MATLAB)/extern/include" -I"$(MATLAB)/simulink/include"
  CFLAGS_OPTIM=-O -DNDEBUG
  CFLAGS_DEBUG=-g
  LDFLAGS=-pthread -Wl,--no-undefined -Wl,-rpath-link,$(MATLAB)/bin/glnxa64 -shared  -L"$(MATLAB)/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -Wl,--version-script,"$(MATLAB)/extern/lib/glnxa64/mexFunction.map"
  LDFLAGS_OPTIM=-O
  LDFLAGS_DEBUG=-g
  MEXSRC=
endif


# R2016b 9.1.0
ifeq ("2016b","$(strip $(MATLAB_VERSION))")
  CFLAGS=-std=c99 -fexceptions -fPIC -fno-omit-frame-pointer -pthread
  CFLAGS+= -D_GNU_SOURCE -DMATLAB_MEX_FILE
  CFLAGS+= -I"$(MATLAB)/extern/include" -I"$(MATLAB)/simulink/include"
  CFLAGS_OPTIM=-O -DNDEBUG
  CFLAGS_DEBUG=-g
  LDFLAGS=-pthread -Wl,--no-undefined -Wl,-rpath-link,$(MATLAB)/bin/glnxa64 -shared  -L"$(MATLAB)/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -Wl,--version-script,"$(MATLAB)/extern/lib/glnxa64/c_exportsmexfileversion.map"
  LDFLAGS_OPTIM=-O
  LDFLAGS_DEBUG=-g
  MEXSRC=$(MATLAB)/extern/version/c_mexapi_version.c
endif

# R2017a 9.2.0
ifeq ("2017a","$(strip $(MATLAB_VERSION))")
  CFLAGS=-fexceptions -fPIC -fno-omit-frame-pointer -pthread
  CFLAGS+= -DTARGET_API_VERSION=700 -DUSE_MEX_CMD -D_GNU_SOURCE -DMATLAB_MEX_FILE
  CFLAGS+= -I"$(MATLAB)/extern/include" -I"$(MATLAB)/simulink/include"
  CFLAGS_OPTIM=-O -DNDEBUG
  CFLAGS_DEBUG=-g
  LDFLAGS=-pthread -Wl,--no-undefined -Wl,-rpath-link,$(MATLAB)/bin/glnxa64 -shared  -L"$(MATLAB)/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -Wl,--version-script,"$(MATLAB)/extern/lib/glnxa64/c_exportsmexfileversion.map"
  LDFLAGS_OPTIM=-O
  LDFLAGS_DEBUG=-g
  MEXSRC=$(MATLAB)/extern/version/c_mexapi_version.c
endif

# R2017b 9.3.0
ifeq ("2017b","$(strip $(MATLAB_VERSION))")
  CFLAGS=-fexceptions -fPIC -fno-omit-frame-pointer -pthread
  CFLAGS+= -DUSE_MEX_CMD -D_GNU_SOURCE -DMATLAB_MEX_FILE
  CFLAGS+= -I"$(MATLAB)/extern/include" -I"$(MATLAB)/simulink/include"
  CFLAGS_OPTIM=-O -DNDEBUG
  CFLAGS_DEBUG=-g
  LDFLAGS=-pthread -Wl,--no-undefined -Wl,-rpath-link,$(MATLAB)/bin/glnxa64 -shared  -L"$(MATLAB)/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -Wl,--version-script,"$(MATLAB)/extern/lib/glnxa64/c_exportsmexfileversion.map"
  LDFLAGS_OPTIM=-O
  LDFLAGS_DEBUG=-g
  MEXSRC=$(MATLAB)/extern/version/c_mexapi_version.c
endif

# R2018a 9.4.0
ifeq ("2018a","$(strip $(MATLAB_VERSION))")
  CFLAGS=-fexceptions -fPIC -fno-omit-frame-pointer -pthread
  CFLAGS+= -DMATLAB_DEFAULT_RELEASE=R2017b -DUSE_MEX_CMD -D_GNU_SOURCE -DMATLAB_MEX_FILE
  CFLAGS+= -I"$(MATLAB)/extern/include" -I"$(MATLAB)/simulink/include"
  CFLAGS_OPTIM=-O -DNDEBUG
  CFLAGS_DEBUG=-g
  LDFLAGS=-pthread -Wl,--no-undefined -Wl,-rpath-link,$(MATLAB)/bin/glnxa64 -shared  -L"$(MATLAB)/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -Wl,--version-script,"$(MATLAB)/extern/lib/glnxa64/c_exportsmexfileversion.map"
  LDFLAGS_OPTIM=-O
  LDFLAGS_DEBUG=-g
  MEXSRC=$(MATLAB)/extern/version/c_mexapi_version.c
endif

# R2018b 9.5.0
ifeq ("2018b","$(strip $(MATLAB_VERSION))")
  CFLAGS=-fexceptions -fPIC -fno-omit-frame-pointer -pthread
  CFLAGS+= -DMX_COMPAT_64 -DMATLAB_DEFAULT_RELEASE=R2017b -DUSE_MEX_CMD -D_GNU_SOURCE -DMATLAB_MEX_FILE
  CFLAGS+= -I"$(MATLAB)/extern/include" -I"$(MATLAB)/simulink/include"
  CFLAGS_OPTIM=-O2 -fwrapv -DNDEBUG
  CFLAGS_DEBUG=-g
  LDFLAGS=-pthread -Wl,--no-undefined -Wl,-rpath-link,$(MATLAB)/bin/glnxa64 -shared  -L"$(MATLAB)/bin/glnxa64" -lmx -lmex -lmat -lm -lstdc++ -Wl,--version-script,"$(MATLAB)/extern/lib/glnxa64/c_exportsmexfileversion.map"
  LDFLAGS_OPTIM=-O
  LDFLAGS_DEBUG=-g
  MEXSRC=$(MATLAB)/extern/version/c_mexapi_version.c
endif
